AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Stable Diffusion Web UI by Automatic1111

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sd-webui-sg
      GroupDescription: Security group for SD WebUI EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7860
          ToPort: 7860
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: g4dn.xlarge
      ImageId: ami-02f986bab3de34d0d
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
      Tags:
        - Key: Name
          Value: sd-web-ui-cf
      SecurityGroups:
        - Ref: SecurityGroup
      UserData:
        'Fn::Base64': |
          #!/bin/bash
          set -ex
          exec > /var/log/user-data.log 2>&1
          export GIT_TERMINAL_PROMPT=0
          export HOME=/home/ec2-user

          dnf install -y git
          cd /home/ec2-user
          sudo -u ec2-user git clone https://github.com/danbornman/stable-diffusion-webui.git
          bash /home/ec2-user/stable-diffusion-webui/setup.sh

  MyEIP:
    Type: AWS::EC2::EIP

  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref EC2Instance
